version: 2.1

commands:
  base-install:
    parameters:
      package:
        type: string
        default: all
    steps:
      - checkout
      - run: ./.circleci/base-install.sh << parameters.package >>

jobs:
  test-package:
    docker:
      - image: mozilla/fxa-circleci
      - image: redis
      - image: memcached
      - image: pafortin/goaws
      - image: circleci/mysql:5.7.27
    parameters:
      package:
        type: string
    environment:
      SKIP_PACKAGES: true
      SKIP_DOCKER: true
    steps:
      - base-install:
          package: << parameters.package >>
      - run: ./.circleci/test-package.sh << parameters.package >>

  test-many:
    docker:
      - image: circleci/node:12
      - image: circleci/mysql:5.7.27
      - image: jdlk7/firestore-emulator
      - image: memcached
      - image: redis
    environment:
      SKIP_PACKAGES: true
      SKIP_DOCKER: true
    steps:
      - base-install
      - run:
          name: Testing...
          command: |
            PACKAGES=(\
            '123done' \
            'browserid-verifier' \
            'fortress' \
            'fxa-admin-panel' \
            'fxa-admin-server' \
            'fxa-auth-client' \
            'fxa-auth-db-mysql' \
            'fxa-customs-server' \
            'fxa-email-event-proxy' \
            'fxa-event-broker' \
            'fxa-geodb' \
            'fxa-js-client' \
            'fxa-payments-server' \
            'fxa-profile-server' \
            'fxa-shared' \
            'fxa-support-panel' \
            )
            for p in "${PACKAGES[@]}"; do
              ./.circleci/test-package.sh $p
            done

  test-content-server:
    parallelism: 6
    docker:
      - image: mozilla/fxa-circleci
      - image: redis
      - image: memcached
      - image: pafortin/goaws
      - image: circleci/mysql:5.7.27
      - image: mozilla/fxa-email-service
        environment:
          NODE_ENV: dev
          FXA_EMAIL_ENV: dev
          FXA_EMAIL_LOG_LEVEL: debug
          RUST_BACKTRACE: 1
    environment:
      SKIP_PACKAGES: false
      SKIP_DOCKER: true
    steps:
      - base-install:
          package: fxa-content-server
      - run: ./.circleci/test-package.sh fxa-content-server
      - store_artifacts:
          path: ~/.pm2/logs
          destination: logs
      - store_artifacts:
          path: ~/screenshots
          destination: screenshots

  test-email-service:
    resource_class: large
    docker:
      - image: mozilla/fxa-circleci
      - image: mysql:5.7.27
        environment:
          - MYSQL_DATABASE: fxa
          - MYSQL_ALLOW_EMPTY_PASSWORD: yes
          - MYSQL_ROOT_PASSWORD: ""
      - image: redis
    environment:
      SKIP_PACKAGES: true
      SKIP_DOCKER: true
    steps:
      - base-install:
          package: fxa-email-service
      - run: ./packages/fxa-email-service/scripts/test-ci.sh
      - store_artifacts:
          path: artifacts

  test-fxa-circleci:
    resource_class: small
    docker:
      - image: circleci/node:12
    environment:
      SKIP_PACKAGES: true
      SKIP_DOCKER: true
    steps:
      - base-install:
          package: fxa-circleci
      - setup_remote_docker
      - run: ./.circleci/build.sh fxa-circleci

  deploy-packages:
    resource_class: small
    docker:
      - image: circleci/node:12
    environment:
      SKIP_PACKAGES: true
      SKIP_DOCKER: true
    steps:
      - base-install
      - setup_remote_docker
      - run:
          name: Build docker images
          command: ./.circleci/build-all.sh
          no_output_timeout: 1h
      - run:
          name: Push to docker hub
          command: ./.circleci/deploy-all.sh
      - store_artifacts:
          path: artifacts

workflows:
  test_pull_request:
    jobs:
      - test-many:
          filters:
            branches:
              ignore: master
            tags:
              ignore: /.*/
      - test-package:
          name: test-auth-server
          package: fxa-auth-server
          filters:
            branches:
              ignore: master
            tags:
              ignore: /.*/
      - test-content-server:
          filters:
            branches:
              ignore: master
            tags:
              ignore: /.*/
      - test-email-service:
          # since email-service is expensive
          # to build and rarely changes
          # we only run it on branches
          # starting with "email-service-"
          filters:
            branches:
              only:
                - /^email-service-.*/
            tags:
              ignore: /.*/
      - test-fxa-circleci:
          # since fxa-circleci rarely changes
          # we only run it on branches
          # starting with "fxa-circleci-"
          filters:
            branches:
              only:
                - /^fxa-circleci-.*/
            tags:
              ignore: /.*/
  deploy_master:
    jobs:
      - deploy-packages:
          filters:
            branches:
              only: master
            tags:
              ignore: /.*/
  test_and_deploy_tag:
    jobs:
      - test-many:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - test-package:
          name: test-auth-server
          package: fxa-auth-server
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - test-content-server:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - deploy-packages:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
          requires:
            - test-many
            - test-auth-server
            - test-content-server
